package dev.fuju.core.error

/**
 * AuthCore / Fuju Backend が返す error code の辞書。
 * `../auth-component/src/ErrorCodes.ts` の 33 種を 1:1 で移植し、さらに [UNKNOWN] を追加。
 *
 * wire format は string code（`enum.name` と同じ）。不明な code は [UNKNOWN] に寄せる。
 */
enum class ErrorCode(
    val wire: String,
) {
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    EMAIL_NOT_VERIFIED("EMAIL_NOT_VERIFIED"),
    PUBLIC_ID_ALREADY_EXISTS("PUBLIC_ID_ALREADY_EXISTS"),
    PUBLIC_ID_RESERVED("PUBLIC_ID_RESERVED"),
    PUBLIC_ID_FORMAT_INVALID("PUBLIC_ID_FORMAT_INVALID"),
    EMAIL_INVALID("EMAIL_INVALID"),
    PASSWORD_TOO_SHORT("PASSWORD_TOO_SHORT"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_INVALID("TOKEN_INVALID"),
    TOKEN_REVOKED("TOKEN_REVOKED"),
    TOKEN_MALFORMED("TOKEN_MALFORMED"),
    MFA_REQUIRED("MFA_REQUIRED"),
    MFA_NOT_ENABLED("MFA_NOT_ENABLED"),
    MFA_ALREADY_ENABLED("MFA_ALREADY_ENABLED"),
    TOTP_CODE_INVALID("TOTP_CODE_INVALID"),
    RECOVERY_CODE_INVALID("RECOVERY_CODE_INVALID"),
    CLIENT_INVALID("CLIENT_INVALID"),
    CLIENT_NOT_FOUND("CLIENT_NOT_FOUND"),
    SOCIAL_PROVIDER_INVALID("SOCIAL_PROVIDER_INVALID"),
    SOCIAL_AUTH_FAILED("SOCIAL_AUTH_FAILED"),
    INVALID_REQUEST("INVALID_REQUEST"),
    MISSING_REQUIRED_FIELD("MISSING_REQUIRED_FIELD"),
    RATE_LIMIT_EXCEEDED("RATE_LIMIT_EXCEEDED"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),
    FILE_FORMAT_INVALID("FILE_FORMAT_INVALID"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),
    NETWORK_ERROR("NETWORK_ERROR"),

    /** サーバーが未知の code を返したときのフォールバック。 */
    UNKNOWN("UNKNOWN"),
    ;

    companion object {
        private val byWire: Map<String, ErrorCode> = entries.associateBy { it.wire }

        fun fromWireOrUnknown(value: String?): ErrorCode {
            if (value == null) return UNKNOWN
            return byWire[value] ?: UNKNOWN
        }
    }
}
